name: Process URLs and Save Files

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次

jobs:
  process_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出仓库代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 指定Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Change wrapper permissions
        run: chmod +x scripts/convert_list.py
        
      - name: Run script
        run: python scripts/convert_list.py  # 运行你的Python脚本

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update output files" -a
        continue-on-error: true  # 如果没有变化导致提交失败，不会使整个工作流失败

      - name: Push changes
        run: |
          git fetch
          git push https://${{ secrets.CONVERT }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
        env:
          GIT_AUTHOR_EMAIL: action@github.com
          GIT_COMMITTER_EMAIL: action@github.com
        continue-on-error: true  # 如果没有变化导致推送失败，不会使整个工作流失败
