name: test

on:
  push:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  sync_and_compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Fetch Sing-Box Rules from ruleset
      run: |
        git remote add ruleset https://github.com/gaoyifan/china-operator-ip
        git fetch ruleset
        git checkout ruleset/ip-lists -- china.txt china6.txt
        git add .
        git push
